#!/usr/bin/env bash

echo >&2 "starting pre-push hook"
make clean dist
if ! [[ $? -eq 0 ]]; then
	echo >&2 "Can't build, not pushing"
	exit 1
fi

echo >&2 "looks fine, cleaning up after myself"
make clean

exit 0
