#!/usr/bin/env bash

YELLOW="\033[0;33m"
GREEN="\033[0;32m"
RED="\033[0;32m"
RESET="\033[0m"

function info() {
	printf "%b%b%b\n" $YELLOW "$1" $RESET >&2
}

function err() {
	printf "%b%b%b\n" $RED "$1" $RESET >&2
}

function succ() {
	printf "%b%b%b\n" $GREEN "$1" $RESET >&2
}

SCORE="\xF0\x9F\x8E\xBC"
info "$SCORE starting pre-push hook"
make lint clean dist
if ! [[ $? -eq 0 ]]; then
	err "can't build, not pushing"
	exit 1
fi

succ "looks fine, cleaning up after myself"
make clean

exit 0
